/* THIS INFO IS PUBLIC ONLY FOR EDUCATIONAL PURPOSES */
CREATE TABLE users (
    id serial AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(100) NOT NULL,
    user_login VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    birth_date TIMESTAMP NULL DEFAULT NULL,
    country_id SMALLINT NOT NULL
) AUTO_INCREMENT = 1;